### ISSUE TITLE
110 题目里面的链接打不开了

### ISSUE THREAD

**Issue by yydaily** [PE-CN/PE-CN.github.io#10]
点击链接，应该是链接到108题目，但是实际跳转到 [这里](https://pe-cn.github.io/Problem101-125/#Problem_108)，一个github的404页面，打开失败了。

**Comment by yydaily** [comment]
110的翻译 [原链接](https://pe-cn.github.io/110/)

**Comment by sx349** [comment]
已修改（最初采用过每页面25题翻译的做法，后来发现并不方便就改成了单独页面，属于历史遗留问题），将在下次部署时更新。谢谢指出!
