### ISSUE TITLE
PE 126

### ISSUE THREAD

**Issue by yydaily** [PE-CN/PE-CN.github.io#13]
翻译链接：[https://pe-cn.github.io/126/](https://pe-cn.github.io/126/)
原题链接：[https://projecteuler.net/problem=126](https://projecteuler.net/problem=126)
原文：If we then add a second layer to this solid it would require forty-six cubes to cover every visible face, the third layer would require seventy-eight cubes, and the fourth layer would require **one-hundred and eighteen** cubes to cover every visible face.
翻译：如果我们要再包一层，需要46个立方体才能挡住所有表面，而第三层需要78个立方体，第4层则需要**180**个立方体。

数字翻译错误了，辛苦更正下~

**Comment by PE-CN** [comment]
Done :)
