### ISSUE TITLE
Problem 800 翻译有误

### ISSUE THREAD

**Issue by weilycoder** [PE-CN/PE-CN.github.io#17]
如题。

原文为 “We define $C(n)$ to be the number of hybrid-integers less than or equal to $n$.”

翻译为 “定义 $C(n)$ 为小于等于 $n$ 的所有混合整数之和。”

应为 “定义 $C(n)$ 为小于等于 $n$ 的所有混合整数的个数。”

**Comment by sx349** [comment]
已更正，谢谢。
